### PR TITLE
Grid resize on size allocation

### PR DESCRIPTION
**Pull request by nikolaizombie1**
This addresses issue #109.

### CODE REVIEW

**Comment by anufrievroman** [comment]
Thank you! I'm checking it, a small question, is there any reason to use math.floor instead of just integer division, like `attribution // width`?

**Comment by nikolaizombie1** [comment]
> Thank you! I'm checking it, a small question, is there any reason to use math.floor instead of just integer division, like `attribution // width`?

There really is no reason why. I'm just not familiar enough with the // operator.

**Comment by anufrievroman** [comment]
I thought maybe there's a trick or some type issue. Okay, I'll check again and merge tomorrow.

**Comment by anufrievroman** [comment]
Actually, to me it doesn't work as intended. At least on hyperland (which might be the primary platform for this app) it works when I make window larger, but not when I make it smaller. It stuck with the large grid and cannot be resized back to small size. So, I had to revert the merge.

**Comment by nikolaizombie1** [comment]
> Actually, to me it doesn't work as intended. At least on hyperland (which might be the primary platform for this app) it works when I make window larger, but not when I make it smaller. It stuck with the large grid and cannot be resized back to small size. So, I had to revert the merge.

Yeah, saw the issue happen on my NixOS hyprland install but I chocked it up to NixOS being wonky. I'm going to check on Sway first to see if it's a problem with tiling Window managers as a whole or if it's a hyprland specific issue. If it is a hyprland specific issue I'll contact them and see what could be done of the situation.

**Pull request merged**
