### PR TITLE
Configuration fixes, translations and bug fixes

### PR DESCRIPTION
**Pull request by Thaodan**
This pull request contains the following changes:
- Retrieve metadata such as version, homePage
  and other from python package metadata with importlib
- Retrieve configuration, cache and pictures directory
  from platformdirs (uses XDG)
- Add workarounds in case GdkPixbuf can't generate thumbnails
  for images that are contained in a folder
  - Examples are images that have zero bytes or the
    wrong file extension
  - right now they are excluded but it might be better
    to use a placeholder image instead
- Replace Python based translation that used
  forbidden or frowned with gettext [upon](https://stackoverflow.com/a/55722824/1623839)
  - Add Python script to generate, update translations
    and their template
  - Translate some areas that previously were not translated
  - Import translations into gettext
    - English
    - German
    - French
  - Add setuptools-gettext to build and install translations
- Update documentation

### CODE REVIEW

**Comment by Thaodan** [comment]
Roman ***@***.***> writes:

> Hi, thanks for a lot of work! It looks great, but I'll need some time
> to review this. I have a few questions at the moment:
> - **Retrieve metadata** looks reasonable, but for me the application
> doesn't run anymore because `importlib_metadata.PackageNotFoundError:
> No package metadata was found for waypaper`. Does it mean I have to
> install it into the system to run it? I mean, where are the metadata
> stored now?

Did you install the package during development with pipx (or a similar
tool)? The meta is stored in the .dist-info directory inside
python site-packages directory.
It is installed when installing the package wheel.

> - **Retrieve configuration, cache and pictures directory** - Okay.
> - **Add workarounds in case GdkPixbuf can't generate thumbnails** - Okay
> - **Replace Python based translation** - Looks cool, but I don't
> really understand how it works now :D I'll try to read about gettext,
> but if you have some link where it is explained or you could explain
> it here, it would be much appreciated.

Any tutorial is fine but the gist how gettext works is:
Instead of writing the raw english text inside your application you call
gettext with the english text.
To make this easier to type the gettext function is usually
aliased to `_`.
Gettext then looks for a translation of that text inside the translation
of your application and replaces your English text with the language of
the user at runtime, unless you don't tell it explicitly what language
to use.
You can use format strings or fstrings to insert templates
into the translatable string e.g. `_("Hello {user}".format(user=user)`.

During development after adding new strings to the application the
developer has to call xgettext to extract the new string into the
translation template.
After doing so the existing translations will be update when `msgmerge`
is called to merge the old translation with the template.

A new translation is called with msginit in the po directory.
After this is done the user has to translate the original
message in msgid with their translation into msgstr.
For convenience the location of text is shown inside the
template for the user to see where the actual text is.
The process is repeated when the transmission will be updated.
The user can as well use graphical applications such as Localize to
help translating.
There are also various webservices such as weblate for this process that
support gettext.

During install setuptools-gettext installs all translations
as if there would be any python file in your project.

**Comment by anufrievroman** [comment]
Thank you for the explanations, very interesting. So:
- **Metadata** also works, okay. A small question: so, now all metadata is initially stored in `setup.py`, and then placed into PKG_INFO upon install, right?
- **Version** - now your version is 0.0.2, let's call it 2.1.0.
- **Translations** - looks like it works fine, give me a few days to fully understand this system. A small question: so now it picks up the language from user's locale, right? And the config parameter `language` is ignored? If so, I think it is a reasonable behavior, but then let's remove the `language` from config.

**Comment by Thaodan** [comment]
Roman ***@***.***> writes:

> Thank you for the explanations, very interesting. So:
> - **Metadata** also works, okay. A small question: so, now all
> metadata is initially stored in `setup.py`, and then placed into
> PKG_INFO upon install, right?
> - **Version** - now your version is 0.0.2, let's call it 2.1.0.

Yes, I can fix that version number. Another way it to use setuptools-scm:
https://github.com/pypa/setuptools_scm

> - **Translations** - looks like it works fine, give me a few days to
> fully understand this system. A small question: so now it picks up the
> language from user's locale, right? And the config parameter
> `language` is ignored? If so, I think it is a reasonable behavior, but
> then let's remove the `language` from config.

Yes, you can test by using LANG=de waypaper fro example. Some
application have language options but for this it seems simple enough.

**Comment by anufrievroman** [comment]
> Yes, you can test by using LANG=de waypaper fro example. Some application have language options but for this it seems simple enough.
In my case, this results in:
```
Locale not supported by C library.
Using the fallback 'C' locale.
```

**Comment by anufrievroman** [comment]
Another little issue I noticed, I am not quite clear where the cache is now saved and read from. When I run:
```
platformdirs.user_cache_dir("waypaper")
```
The response is logically `~/.cache/waypaper` but this folder is actually empty. Cache in venv seems empty as well. Yet the previews are clearly generated and stored somewhere, but where? And when I "Refresh" it is instantly completed, as if it didn't actually deleted and re-cached all images, so I suspect something might be wrong here. Looking at the code, everything seems fine, but where are the thumbnails actually?

**Comment by Thaodan** [comment]
>> Yes, you can test by using LANG=de waypaper fro example. Some
> application have language options but for this it seems simple enough.
> In my case, this results in:
> ```
> Locale not supported by C library.
> Using the fallback 'C' locale.
> ```

I got the same message but the translations where used anyway, the error
is about the translation in glibc not being enabled.

**Comment by Thaodan** [comment]
> Another little issue I noticed, I am not quite clear where the cache is now saved and read from. When I run:
> 
> ```
> platformdirs.user_cache_dir("waypaper")
> ```
> 
> The response is logically `~/.cache/waypaper` but this folder is actually empty (it is probably created when Config() is initiated). Cache in venv seems empty as well. Yet the previews are clearly generated and stored somewhere, but where? And when I "Refresh" it is instantly completed, as if it didn't actually delete and re-cache all images, so I suspect something might be wrong here. Looking at the code, everything seems fine, but where are the thumbnails actually? I also tried to modify an image (but keep the name) and click "Refresh", the changes are not reflected, so refresh doesn't really work.
> 

I forgot the slash in the cache path, I switched the code to use pathlib instead.
It's very easy to combine paths wrong when using strings.

> p.s. also both Config() and App() have the property `cacheDir`, which used here and there. I think only config's `cacheDir` is enough, and maybe that's why there are two different cache locations somehow.

cacheDir (or now cachePath) is set during runtime from XDG_CACHE_HOME, since both are properties of each class they have to be defined in both.
cacheDir exists in config to create the directory since only config is both called by main and by the app class.

**Comment by anufrievroman** [comment]
I am afraid this version is even more problematic than before. I am trying to figure it out, but so far I see:
1. `Refresh` just makes all thumbnails in GUI disappear.
2. When I close and restart the app after `Refresh`, it shows only one thumbnail instead of many that are in the folder. Then, closing it again and starting again works as intended.
3. Minor point, but I noticed you changed initiation as `self.wallpaper = str()` in config, but actually `self.wallpaper` needs to be a list of wallpapers corresponding to each monitor in `self.monitors`.

**Comment by Thaodan** [comment]
>     3. Minor point, but I noticed you changed initiation as `self.wallpaper = str()` in config, but actually `self.wallpaper` needs to be a list of wallpapers corresponding to each monitor in `self.monitors`.

Oh I think I have changed that by accident because of this line further down below:
```
self.wallpaper_str = config.get("Settings", "wallpaper", fallback=self.wallpaper, raw=True)
```

Here fallback will be self.wallpaper which isn't a string. Fallback should be str in this case.

Will fix.

**Comment by anufrievroman** [comment]
I tested more, basically something wrong with this part in `app.py`
```
 if not cache_image(image_path, self.cachePath):
       # Cache image didn't work move on to next image
       self.image_paths.remove(image_path)
        continue
```
It skips many valid images for some reason, and Refresh function breaks. If we simply replace it, as it was, by:
```
cache_image(image_path, self.cachePath)
```
Then everything works as expected. Except, I suppose, there is will be a problem when image mime type is mismatched.
To be honest, I don't clearly see why it behaves this way. If you don't see either, let's just try to solve the (rare) mime-type mismatch problem differently.

**Comment by Thaodan** [comment]
Thanks I will look at it next week.

**Comment by Thaodan** [comment]
Sorry I didn't found the time to fix the issues in this PR feel free to amend my changes.

**Comment by anufrievroman** [comment]
No worries, I also didn't have much time to work on waypaper, so I decided to grab this PR into a separate branch and gradually cherrypick commits from it.

**Comment by anufrievroman** [comment]
Hi, thank you again for your contribution. Just wanted to note that I merged your commits about paths, meta and some other things. Then I dealt with the non-rendering images by using placeholders, so that you get a black image in the list. The translations I didn't really understand the gettxt, so I solved the issue of global import by remaking the translation file as a class, so I'll keep it like that for now.

**Comment by Thaodan** [comment]
Sure. I don't necessarily understand what is there not to understand about gettext. You put the base text in, it spits out a file for translators to put there strings in and gettext will take care of replacing the base text with the translation.

The plus for you besides the automatic language selection is that translators don't have to be programmers.

**Pull request merged**
