### PR TITLE
enhancement: Add type annotations to code base

### PR DESCRIPTION
**Pull request by nikolaizombie1**
I added type annotations to the `wapaper` code base so that it is easier to understand functions at a glance. This PR addresses part of #49 .

### CODE REVIEW

**Comment by anufrievroman** [comment]
Great job! Thank you. But let's remove the requirements and gitignore files, it seems to be more of a personal development environment preferences.

**Comment by nikolaizombie1** [comment]
> Great job! Thank you. But let's remove the requirements and gitignore files, it seems to be more of a personal development environment preferences.

For the requirements file, it was en error uploading it, but the gitignore was to avoid the upload of `venv` or `pycache` files to the repository. But if you want removed I'll do it.

**Comment by anufrievroman** [comment]
Okay, let's keep gitignore then

**Comment by nikolaizombie1** [comment]
The requirements file was removed.

**Pull request merged**
