### PR TITLE
added new swww transition menu feature.

### PR DESCRIPTION
**Pull request by Sandesh2007**
This change adds new swww transition menu feature and added translation for changes done to the feature's tooltop.

**Signed-off-by: Sandesh2007 <sandeshsharma924@gmail.com>**

### CODE REVIEW

**Comment by anufrievroman** [comment]
Hi, thank you for your work! I'll try review the PR in a few days. In general, I was actually thinking to make a second line of buttons/options specific to swww. Like other transition related options all in one line below the main line of buttons that are common for all backends. If, by chance, you know how to make a new line of buttons for your swww transition button then it would be great to make it that way. If not, it's okay, I'll try to work on it in the near future.

**Comment by Sandesh2007** [comment]
sure i will give it a shot :)

**Comment by Sandesh2007** [comment]
**Done.**
Added new menu to set different options for swww backend.

**Comment by anufrievroman** [comment]
Sorry, I still didn't have time to test it, will try to do within a week

**Comment by Sandesh2007** [comment]
Sure, I will wait for your response.
This is the first time i am contributing to a open source project and this project really helped me to learn making apps for linux in python Gtk. Thank you :)

**Comment by anufrievroman** [comment]
Hi, I am working on your PR, it looks pretty good, but you should do the changes related to the search bar in a separate branch because all the commits related to that are now also added here, to this PR, which makes it a bit difficult. If you could roll back changes in your main branch to the moment before the search bar, and add all search-bar commits on the separate branch, it would be great. If you aren't sure how to do that, may I can then wait when you complete the search bar as well.

**Comment by Sandesh2007** [comment]
I have completed the search bar, but there is the keybonding problem.(searching images also triggers the keybinds) I will try to fix it if i could. I am new to this it would be great if you could tell what should i change.

**Comment by anufrievroman** [comment]
The quick solution I can think of, is you create a global variable like `seach_state = True` which activates when the widget is active, and then this variable is checked in `on_key_pressed()` function, like:
```
if search_state:
    return
```
So that the other key bindings are not triggered.

Or maybe, another way, the on_key_pressed() function can simply check if search bar is empty, before continuing.

**Comment by Sandesh2007** [comment]
Thanks i was confused on how to fix it, but now it is done.

when the search bar is focused, the keybinding will not work and clicking on the clear button will remove focus from button and the key binding will work.

i will commit the changes in few minutes.

**Comment by anufrievroman** [comment]
Thank you again, I'll try to check it today.

**Comment by anufrievroman** [comment]
By the way, I finally decided to rearrange the UI a bit, so I put all the folder related buttons in the top, and then I could put all backend related options, including transitions, into the bottom row.

**Comment by Sandesh2007** [comment]
I am thinking to make another fork/branch with ai stuff ( wallpaper generator kind of ).
But due to my exams on my head i will work to implement it. Maybe waypaper-ai/ waypaper-adv l. Not for public maybe. 🤜🏾🤛🏾

**Pull request merged**
