### PR TITLE
Add --monitor user argument for CLI

### PR DESCRIPTION
**Pull request by WilliamG99**
Solves issue #94 
Added parser argument and logic to main, refactored get_monitors_names() to solve circular import and updated translations.

### CODE REVIEW

**Comment by anufrievroman** [comment]
Thank you! I'll check it in more details, but preliminarily, line 65 will probably fail if neither `--wallpaper` not `--random` was provided, only `--monitor`, and so `wallpaper` variable is not assigned. Maybe the upper if statement should include the requirement of either `args.wallpapers` or `args.random`?

**Comment by anufrievroman** [comment]
Also, instead of creating a whole new module `getmonitors`, maybe let's just to add a little snippet when we need it:
```
connected_monitors: List[str] = []
for m in screeninfo.get_monitors():
    connected_monitors.append(m.name)
```
It is used only in two places, I think.

**Comment by WilliamG99** [comment]
Hey, thanks for the feedback.
I've fixed the two problems now. `--monitor` will not work without `--wallpaper` or `--random` and I've also replaced get_monitors.py with your suggestion.

For the monitor argument checks I have written...
`if args.monitor and not args.wallpaper and not args.random: 
    print("--monitor Error! Requires an image to be set\nUse --wallpaper or --random")
    sys.exit(0)`
It just uses a print() to display the error message. Not sure if this is fine. What is the correct way to call an error message?

**Comment by anufrievroman** [comment]
That's alight, thank you for quick changes! I'll test again tomorrow.

**Comment by anufrievroman** [comment]
I merged it and refactored a bit in 84afef9ad1400a395c4a233c1f7f53dbe6061273. Thank you for contribution!

**Comment by WilliamG99** [comment]
Awesome, first time contributing to something. Feels good 😊

**Comment by anufrievroman** [comment]
Welcome to the team :)

**Pull request merged**
